In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

print("A@B:", A@B)
print("B@A:", B@A)

print("A.T@B:", A.T@B)
print("B.T@A:", B.T@A)

print("A@B.T:", A@B.T)
print("B@A.T:", B@A.T)

print("A.T@B.T:", A.T@B.T)
print("B.T@A.T:", B.T@A.T)


"""
D = A @ B * C
print("R1:", D)

D = A @ B 
print(D)

D = D * C
print("R2:", D)

D = B * C
print(D)

D = A @ D
print("R3:", D)

D = D @ A
print("R3_:", D)


D = A.dot(B * C)
print("R4:", D)

D = A.dot(B)
print( D)

D = B.dot(A)
print("_", D)



D = D * C
print("R5:", D)
"""


A@B: [[19 22]
 [43 50]]
B@A: [[23 34]
 [31 46]]
A.T@B: [[26 30]
 [38 44]]
B.T@A: [[26 38]
 [30 44]]
A@B.T: [[17 23]
 [39 53]]
B@A.T: [[17 39]
 [23 53]]
A.T@B.T: [[23 31]
 [34 46]]
B.T@A.T: [[19 43]
 [22 50]]


'\nD = A @ B * C\nprint("R1:", D)\n\nD = A @ B \nprint(D)\n\nD = D * C\nprint("R2:", D)\n\nD = B * C\nprint(D)\n\nD = A @ D\nprint("R3:", D)\n\nD = D @ A\nprint("R3_:", D)\n\n\nD = A.dot(B * C)\nprint("R4:", D)\n\nD = A.dot(B)\nprint( D)\n\nD = B.dot(A)\nprint("_", D)\n\n\n\nD = D * C\nprint("R5:", D)\n'

In [22]:
class Namespace:
    def __init__(self, /, **args):
        for key, value in args.items():
            setattr(self, key, value)

    def especial():
      None

def func4(args):
    args.a = 'new-value'        # args is a mutable Namespace
    args.b = args.b + 1         # change object in-place

args = Namespace(a='old-value', b=99)
func4(args)
vars(args)


{'a': 'new-value', 'b': 100}

In [23]:
dir(Namespace)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'especial']

In [72]:
#@title Producto Punto de dos Matrices
def mult_matrices(A, B):
  #S = []
  s = 0
  #C = [[0,0,0], [0,0,0], [0,0,0]]

  #Inicializa Matriz resultado
  fA, cB  = len(A), len(B[0])    # Filas A, Cols B
  C = [[None] * cB for i in range(fA)]

  #COL B x FIL A
  #print("A-> F:",len(A), "C:",len(A[0]))
  #print("B-> F:",len(B), "C:",len(B[0]))
  #print("\n")

  #fA  = len(A)
  #cB  = len(B[0])
  #D = [0] * 2 # len(B[0]) # *cB
  #C = [D] * 3 #len(A)   # fA
  #C = [[0]*2] * 3 #len(A)   # fA

  for cB in range(len(B[0])): #COL B
    for fA in range(len(A)): #FIL A
      s = 0
      for cA in range(len(A[0])): #COL A
        #for fB in range(cA, cA+1): #len(B)): #FIL B
          fB = cA
          #S.append(A[fA][cA] * B[fB][cB])
          s += A[fA][cA] * B[fB][cB]
          #print(f"A[{fA}, {cA}],  {A[fA][cA]}")
          #print(f"B[{fB}, {cB}],  {B[fB][cB]}")
          #print("\n")
      #S.append("+")
      C[fA][cB] = s

  return C

In [73]:
A = [[1,2], [3,4]]
B = [[5,6], [7,8]]

A = [[3,2,1], [1,1,3], [0,2,1]]
B = [[2,1], [1,0], [3,2]]



mult_matrices(A, B)

[[11, 5], [12, 7], [5, 2]]

In [ ]:
print(len(A), len(A[0]))

2 2


In [11]:
  C = [0] *2
  D = [C] *3
  D,"---", C

([[0, 0], [0, 0], [0, 0]], '---', [0, 0])

In [14]:
D[0][1] = 3
D,"---", C

([[0, 3], [0, 3], [0, 3]], '---', [0, 3])

In [4]:
C=C+C
C

[[5, 0], [5, 0], [5, 0], [5, 0], [5, 0], [5, 0]]

In [17]:
id(C), id(D[0]), id([1]), id(D)

(140283866629568, 140283866629568, 140283866395904, 140283866397120)

In [25]:
C is D[0]

True

In [37]:
  C = [0] *2
  D = [[[0]*2] *3]*2 #[C[:].copy()] *3
  D,"---", C
  D[0][0] = 1
  D

[[1, [0, 0], [0, 0]], [1, [0, 0], [0, 0]]]

In [49]:
A = [0] * 3
for i in range(3):
    A[i] = [None] * 2
A[0][1] = 1
A

[[None, 1], [None, None], [None, None]]

In [50]:
w, h = 2, 3
A = [[None] * w for i in range(h)]
A[0][1] = 1
A

[[None, 1], [None, None], [None, None]]

In [39]:
a = 1
b = a
b = b+1
a,b
id(a), id(b)

(9793088, 9793120)

In [53]:
import copy
B = copy.copy(A)
b = copy.deepcopy(A)
A[1][0] = 2
print(b, B)

[[None, 1], [None, None], [None, None]] [[None, 1], [2, None], [None, None]]


In [19]:
dir(C)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [42]:
def myFunc():
    print("hello")

fname = "myFunc"

f = locals()[fname]
print(dir(f))
print(f)
f()


['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
<function myFunc at 0x7f963922ff70>
hello


In [46]:
class Foo:
    def do_foo(self):
        return 0

    def do_bar(self):
        return 1

opname = 'bar'
foo_instance  = Foo()
f = getattr(foo_instance, 'do_' + opname)
f()


1

In [60]:
from collections.abc import Mapping

class P:
     pass

class C(P):
    pass

Mapping.register(P)


__main__.P

In [62]:
c = C()
isinstance(c, C)        # direct
#True
isinstance(c, P)        # indirect
#True
isinstance(c, Mapping)  # virtual
#True

# Actual inheritance chain
type(c).__mro__
#(<class 'C'>, <class 'P'>, <class 'object'>)

# Test for "true inheritance"
Mapping in type(c).__mro__
#False

(__main__.C, __main__.P, object)

In [67]:
hash("180")

-1461367412523282712

In [ ]:
pip install py2exe

In [ ]:
from py2exe import freeze

In [88]:
import numpy as np

# Creating a 3-D numpy array using np.array()
array = np.array([[12,18,44], [66,37,89],[31,47,88]])
#array = np.array([[[12,18,44], [66,37,89]], [[31,47,88], [31,47,88]]])
print("Original array: ")
print(array)

# using = operator
D = array
D[1][1] = 2
print("\n = arr Copied array: ")
print(array, "\n")
print(D)

# using arr.copy() function
C = array.copy()
C[1][1] = 1
print("\n arr.copy() array: ")
print(array, "\n")
print(C)

# using numpy.copy() function
copy_array = np.copy(array)
print("\n np.copy() Copied array: ")
copy_array[0][0] = 0
print(array, "\n")
print(copy_array)


Original array: 
[[12 18 44]
 [66 37 89]
 [31 47 88]]

 = arr Copied array: 
[[12 18 44]
 [66  2 89]
 [31 47 88]] 

[[12 18 44]
 [66  2 89]
 [31 47 88]]

 arr.copy() array: 
[[12 18 44]
 [66  2 89]
 [31 47 88]] 

[[12 18 44]
 [66  1 89]
 [31 47 88]]

 np.copy() Copied array: 
[[12 18 44]
 [66  2 89]
 [31 47 88]] 

[[ 0 18 44]
 [66  2 89]
 [31 47 88]]


In [137]:
id(C)

140283178867664

In [140]:
C.dtype

dtype('int64')

In [138]:
vars(C.ctypes)

{'_arr': array([[12, 18, 44],
        [ 1, 66, 89],
        [31, 47, 88]]),
 '_ctypes': <module 'ctypes' from '/usr/lib/python3.8/ctypes/__init__.py'>,
 '_data': c_void_p(60847488),
 '_zerod': False}

In [139]:
C.T

array([[12,  1, 31],
       [18, 66, 47],
       [44, 89, 88]])

In [89]:
dir(C)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [130]:
C.std(), C.argmax(), np.squeeze(C), 0 , C

(30.133038346638727, 5, array([[12, 18, 44],
        [ 1, 66, 89],
        [31, 47, 88]]), 0, array([[12, 18, 44],
        [ 1, 66, 89],
        [31, 47, 88]]))

In [122]:
?np.squeeze

In [141]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'C = [0] *2\nC = [C] *3\nC',
  'C[0][0] = 5\nC',
  'C=C+2\nC',
  'C=C+C\nC',
  'C[0][0] = 55\nC',
  'C[0][1] = 1\nC',
  'C[2][1] = 3\nC',
  'is(C)',
  'id(C)',
  'C = [0] *2\nD = [C] *3\nD, C',
  'C = [0] *2\nD = [C] *3\nD,"---", C',
  'C[2][1] = 3\nD,"---", C',
  'C[0][1] = 3\nD,"---", C',
  'D[0][1] = 3\nD,"---", C',
  'id(C), id(D)',
  'id(C), id(D[0]), id([1]), id(D))',
  'id(C), id(D[0]), id([1]), id(D)',
  "class Namespace:\n    def __init__(self, /, **args):\n        for key, value in args.items():\n            setattr(self, key, value)\n\ndef func4(args):\n    args.a = 'new-value'        # args is a mutable Namespace\n    args.b = args.b + 1         # change object in-place\n\nargs = Namespace(a='old-val

In [142]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'C = [0] *2\nC = [C] *3\nC',
  'C[0][0] = 5\nC',
  'C=C+2\nC',
  'C=C+C\nC',
  'C[0][0] = 55\nC',
  'C[0][1] = 1\nC',
  'C[2][1] = 3\nC',
  'is(C)',
  'id(C)',
  'C = [0] *2\nD = [C] *3\nD, C',
  'C = [0] *2\nD = [C] *3\nD,"---", C',
  'C[2][1] = 3\nD,"---", C',
  'C[0][1] = 3\nD,"---", C',
  'D[0][1] = 3\nD,"---", C',
  'id(C), id(D)',
  'id(C), id(D[0]), id([1]), id(D))',
  'id(C), id(D[0]), id([1]), id(D)',
  "class Namespace:\n    def __init__(self, /, **args):\n        for key, value in args.items():\n            setattr(self, key, value)\n\ndef func4(args):\n    args.a = 'new-value'        # args is a mutable Namespace\n    args.b = args.b + 1         # change object in-place\n\nargs = Namespace(a='old-val

In [143]:
type(C)

numpy.ndarray